import type { Book } from "./types"

export const allBooks: Book[] = [
  {
    id: "1",
    title: "The Midnight Library",
    author: "Matt Haig",
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Would you have done anything different, if you had the chance to undo your regrets?",
    price: 14.99,
    coverImage: "/images/midnight-library.jpg",
    category: "fiction",
    rating: 4.5,
    reviews: 1289,
    publisher: "Viking",
    publicationDate: "August 13, 2020",
    isbn: "978-0525559474",
    pages: 304,
    format: "both",
    reviewsData: [
      {
        author: "Jane Smith",
        rating: 5,
        title: "Life-changing read",
        content:
          "This book completely changed my perspective on life and the choices we make. Beautifully written and deeply moving.",
      },
      {
        author: "John Doe",
        rating: 4,
        title: "Thought-provoking",
        content: "A fascinating concept executed well. Makes you think about all the paths not taken in your own life.",
      },
    ],
  },
  {
    id: "2",
    title: "Atomic Habits",
    author: "James Clear",
    description:
      "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    price: 11.98,
    coverImage: "/images/atomic-habits.jpg",
    category: "self-help",
    rating: 4.8,
    reviews: 2541,
    publisher: "Avery",
    publicationDate: "October 16, 2018",
    isbn: "978-0735211292",
    pages: 320,
    format: "both",
    reviewsData: [
      {
        author: "Michael Johnson",
        rating: 5,
        title: "Life-changing habits",
        content:
          "This book has completely transformed how I approach my daily routines. The 1% improvement concept is brilliant.",
      },
    ],
  },
  {
    id: "3",
    title: "Project Hail Mary",
    author: "Andy Weir",
    description:
      "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it.",
    price: 16.89,
    coverImage: "/images/project-hail-mary.jpg",
    category: "science fiction",
    rating: 4.7,
    reviews: 987,
    publisher: "Ballantine Books",
    publicationDate: "May 4, 2021",
    isbn: "978-0593135204",
    pages: 496,
    format: "both",
    reviewsData: [
      {
        author: "Sarah Williams",
        rating: 5,
        title: "Even better than The Martian",
        content:
          "Andy Weir has outdone himself. The science is fascinating, the characters are compelling, and the story is gripping from start to finish.",
      },
    ],
  },
  {
    id: "4",
    title: "Educated",
    author: "Tara Westover",
    description:
      "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure the children received an education, and no one to intervene when one of Tara's older brothers became violent.",
    price: 13.69,
    coverImage: "/images/educated.jpg",
    category: "memoir",
    rating: 4.6,
    reviews: 1876,
    publisher: "Random House",
    publicationDate: "February 20, 2018",
    isbn: "978-0399590504",
    pages: 352,
    format: "both",
  },
  {
    id: "5",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description:
      "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    price: 12.99,
    coverImage: "/images/silent-patient.jpg",
    category: "thriller",
    rating: 4.3,
    reviews: 1543,
    publisher: "Celadon Books",
    publicationDate: "February 5, 2019",
    isbn: "978-1250301697",
    pages: 336,
    format: "both",
  },
  {
    id: "6",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    description:
      "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl. But Kya is not what they say.",
    price: 9.98,
    coverImage: "/images/crawdads.jpg",
    category: "fiction",
    rating: 4.8,
    reviews: 2198,
    publisher: "G.P. Putnam's Sons",
    publicationDate: "August 14, 2018",
    isbn: "978-0735219090",
    pages: 384,
    format: "both",
  },
  {
    id: "7",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    description:
      "In Sapiens, Dr. Yuval Noah Harari spans the whole of human history, from the very first humans to walk the earth to the radical – and sometimes devastating – breakthroughs of the Cognitive, Agricultural and Scientific Revolutions.",
    price: 15.99,
    coverImage: "/images/sapiens.jpg",
    category: "non-fiction",
    rating: 4.7,
    reviews: 2876,
    publisher: "Harper",
    publicationDate: "February 10, 2015",
    isbn: "978-0062316097",
    pages: 464,
    format: "both",
  },
  {
    id: "8",
    title: "The Four Winds",
    author: "Kristin Hannah",
    description:
      "Texas, 1934. Millions are out of work and a drought has broken the Great Plains. Farmers are fighting to keep their land and their livelihoods as the crops are failing, the water is drying up, and dust threatens to bury them all. One of the darkest periods of the Great Depression, the Dust Bowl era, has arrived with a vengeance.",
    price: 14.49,
    coverImage: "/images/four-winds.jpg",
    category: "historical fiction",
    rating: 4.5,
    reviews: 1032,
    publisher: "St. Martin's Press",
    publicationDate: "February 2, 2021",
    isbn: "978-1250178602",
    pages: 464,
    format: "both",
  },

  // NEW BOOKS - Expanded genres and more books per category

  // More Fiction
  {
    id: "9",
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    description:
      "Reclusive Hollywood icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself.",
    price: 13.99,
    coverImage: "/images/seven-husbands-evelyn-hugo.jpg",
    category: "fiction",
    rating: 4.6,
    reviews: 3421,
    publisher: "Atria Books",
    publicationDate: "June 13, 2017",
    isbn: "978-1501161933",
    pages: 400,
    format: "both",
  },
  {
    id: "10",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    description:
      "Greece in the age of heroes. Patroclus, an awkward young prince, has been exiled to the court of King Peleus and his perfect son Achilles. Despite their differences, Achilles befriends the shamed prince, and as they grow into young men skilled in the arts of war and medicine, their bond blossoms into something deeper.",
    price: 12.49,
    coverImage: "/images/song-of-achilles.jpg",
    category: "fiction",
    rating: 4.7,
    reviews: 2876,
    publisher: "Ecco",
    publicationDate: "September 20, 2011",
    isbn: "978-0062060624",
    pages: 416,
    format: "both",
  },

  // More Science Fiction
  {
    id: "11",
    title: "Dune",
    author: "Frank Herbert",
    description:
      "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the 'spice' melange, a drug capable of extending life and enhancing consciousness.",
    price: 18.99,
    coverImage: "/images/dune.jpg",
    category: "science fiction",
    rating: 4.8,
    reviews: 4521,
    publisher: "Ace",
    publicationDate: "August 1, 1965",
    isbn: "978-0441172719",
    pages: 688,
    format: "both",
  },
  {
    id: "12",
    title: "The Martian",
    author: "Andy Weir",
    description:
      "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone.",
    price: 14.99,
    coverImage: "/images/martian.jpg",
    category: "science fiction",
    rating: 4.6,
    reviews: 3987,
    publisher: "Crown",
    publicationDate: "February 11, 2014",
    isbn: "978-0553418026",
    pages: 369,
    format: "both",
  },

  // Fantasy
  {
    id: "13",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    description:
      "The Name of the Wind tells the story of a man in three parts: a hero, a trickster, and a magician, but not yet a legend. Only a myth. Kvothe has come to be one of the most notorious and mysterious figures of his time.",
    price: 16.99,
    coverImage: "/images/name-of-wind.jpg",
    category: "fantasy",
    rating: 4.5,
    reviews: 2134,
    publisher: "DAW Books",
    publicationDate: "March 27, 2007",
    isbn: "978-0756404079",
    pages: 662,
    format: "both",
  },
  {
    id: "14",
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    description:
      "Roshar is a world of stone and storms. Uncanny tempests of incredible power sweep across the rocky terrain so frequently that they have shaped ecology and civilization alike.",
    price: 19.99,
    coverImage: "/images/way-of-kings.jpg",
    category: "fantasy",
    rating: 4.7,
    reviews: 1876,
    publisher: "Tor Books",
    publicationDate: "August 31, 2010",
    isbn: "978-0765326355",
    pages: 1007,
    format: "both",
  },
  {
    id: "15",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description:
      "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.",
    price: 11.99,
    coverImage: "/images/hobbit.jpg",
    category: "fantasy",
    rating: 4.8,
    reviews: 5432,
    publisher: "Houghton Mifflin",
    publicationDate: "September 21, 1937",
    isbn: "978-0547928227",
    pages: 366,
    format: "both",
  },

  // Mystery
  {
    id: "16",
    title: "Gone Girl",
    author: "Gillian Flynn",
    description:
      "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne's fifth wedding anniversary. Presents are being wrapped and reservations are being made when Nick's clever and beautiful wife disappears.",
    price: 13.99,
    coverImage: "/images/gone-girl.jpg",
    category: "mystery",
    rating: 4.2,
    reviews: 4321,
    publisher: "Crown",
    publicationDate: "June 5, 2012",
    isbn: "978-0307588364",
    pages: 419,
    format: "both",
  },
  {
    id: "17",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    description:
      "Forty years ago, Harriet Vanger disappeared from a family gathering on the island owned and inhabited by the powerful Vanger clan. Her body was never found, yet her uncle is convinced it was murder.",
    price: 12.99,
    coverImage: "/images/girl-dragon-tattoo.jpg",
    category: "mystery",
    rating: 4.4,
    reviews: 3654,
    publisher: "Vintage",
    publicationDate: "September 16, 2008",
    isbn: "978-0307454546",
    pages: 590,
    format: "both",
  },

  // Romance
  {
    id: "18",
    title: "The Hating Game",
    author: "Sally Thorne",
    description:
      "Lucy Hutton and Joshua Templeman hate each other. Not dislike. Not begrudgingly tolerate. Hate. And they have no problem displaying their feelings through a series of ritualistic passive aggressive maneuvers.",
    price: 11.99,
    coverImage: "/images/hating-game.jpg",
    category: "romance",
    rating: 4.3,
    reviews: 2987,
    publisher: "William Morrow Paperbacks",
    publicationDate: "August 9, 2016",
    isbn: "978-0062439598",
    pages: 352,
    format: "both",
  },
  {
    id: "19",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description:
      "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work 'her own darling child' and its vivacious heroine, Elizabeth Bennet, 'as delightful a creature as ever appeared in print.'",
    price: 9.99,
    coverImage: "/images/pride-prejudice.jpg",
    category: "romance",
    rating: 4.6,
    reviews: 6543,
    publisher: "Penguin Classics",
    publicationDate: "January 28, 1813",
    isbn: "978-0141439518",
    pages: 432,
    format: "both",
  },

  // Horror
  {
    id: "20",
    title: "The Shining",
    author: "Stephen King",
    description:
      "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing.",
    price: 14.99,
    coverImage: "/images/shining.jpg",
    category: "horror",
    rating: 4.5,
    reviews: 3876,
    publisher: "Doubleday",
    publicationDate: "January 28, 1977",
    isbn: "978-0307743657",
    pages: 447,
    format: "both",
  },
  {
    id: "21",
    title: "Dracula",
    author: "Bram Stoker",
    description:
      "When Jonathan Harker visits Transylvania to help Count Dracula with a London home purchase, he makes a series of horrific discoveries about his client. Soon afterwards, a number of disturbing incidents unfold in England.",
    price: 10.99,
    coverImage: "/images/dracula.jpg",
    category: "horror",
    rating: 4.3,
    reviews: 2543,
    publisher: "Archibald Constable and Company",
    publicationDate: "May 26, 1897",
    isbn: "978-0486411095",
    pages: 418,
    format: "both",
  },

  // Biography
  {
    id: "22",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    description:
      "Based on more than forty interviews with Jobs conducted over two years—as well as interviews with more than a hundred family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur.",
    price: 17.99,
    coverImage: "/images/steve-jobs.jpg",
    category: "biography",
    rating: 4.4,
    reviews: 2876,
    publisher: "Simon & Schuster",
    publicationDate: "October 24, 2011",
    isbn: "978-1451648539",
    pages: 656,
    format: "both",
  },
  {
    id: "23",
    title: "Becoming",
    author: "Michelle Obama",
    description:
      "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her—from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work.",
    price: 16.99,
    coverImage: "/images/becoming.jpg",
    category: "biography",
    rating: 4.7,
    reviews: 4321,
    publisher: "Crown",
    publicationDate: "November 13, 2018",
    isbn: "978-1524763138",
    pages: 448,
    format: "both",
  },

  // Business
  {
    id: "24",
    title: "Good to Great",
    author: "Jim Collins",
    description:
      "Built to Last, the defining management study of the nineties, showed how great companies triumph over time and how long-term sustained performance can be engineered into the DNA of an enterprise from the very beginning.",
    price: 15.99,
    coverImage: "/images/good-to-great.jpg",
    category: "business",
    rating: 4.3,
    reviews: 1987,
    publisher: "HarperBusiness",
    publicationDate: "October 16, 2001",
    isbn: "978-0066620992",
    pages: 320,
    format: "both",
  },
  {
    id: "25",
    title: "The Lean Startup",
    author: "Eric Ries",
    description:
      "Most startups fail. But many of those failures are preventable. The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.",
    price: 14.99,
    coverImage: "/images/lean-startup.jpg",
    category: "business",
    rating: 4.2,
    reviews: 2543,
    publisher: "Crown Business",
    publicationDate: "September 13, 2011",
    isbn: "978-0307887894",
    pages: 336,
    format: "both",
  },

  // Philosophy
  {
    id: "26",
    title: "Meditations",
    author: "Marcus Aurelius",
    description:
      "Written in Greek by the only Roman emperor who was also a philosopher, without any intention of publication, the Meditations of Marcus Aurelius offer a remarkable series of challenging spiritual reflections and exercises developed as the emperor struggled to understand himself and make sense of the universe.",
    price: 8.99,
    coverImage: "/images/meditations.jpg",
    category: "philosophy",
    rating: 4.5,
    reviews: 1876,
    publisher: "Penguin Classics",
    publicationDate: "180 AD",
    isbn: "978-0140449334",
    pages: 254,
    format: "both",
  },
  {
    id: "27",
    title: "The Republic",
    author: "Plato",
    description:
      "The Republic is a Socratic dialogue, authored by Plato around 375 BC, concerning justice, the order and character of the just city-state, and the just man.",
    price: 12.99,
    coverImage: "/images/republic.jpg",
    category: "philosophy",
    rating: 4.2,
    reviews: 987,
    publisher: "Penguin Classics",
    publicationDate: "375 BC",
    isbn: "978-0140455113",
    pages: 416,
    format: "both",
  },

  // Poetry
  {
    id: "28",
    title: "Milk and Honey",
    author: "Rupi Kaur",
    description:
      "Milk and honey is a collection of poetry and prose about survival. About the experience of violence, abuse, love, loss, and femininity. The book is divided into four chapters, and each chapter serves a different purpose.",
    price: 10.99,
    coverImage: "/images/milk-honey.jpg",
    category: "poetry",
    rating: 4.1,
    reviews: 3421,
    publisher: "Andrews McMeel Publishing",
    publicationDate: "November 4, 2014",
    isbn: "978-1449474256",
    pages: 208,
    format: "both",
  },
  {
    id: "29",
    title: "The Sun and Her Flowers",
    author: "Rupi Kaur",
    description:
      "From Rupi Kaur, the #1 New York Times bestselling author of milk and honey, comes her long-awaited second collection of poetry. A vibrant and transcendent journey about growth and healing. Ancestry and honoring one's roots. Expatriation and rising up to find a home within yourself.",
    price: 11.99,
    coverImage: "/images/sun-flowers.jpg",
    category: "poetry",
    rating: 4.3,
    reviews: 2876,
    publisher: "Andrews McMeel Publishing",
    publicationDate: "October 3, 2017",
    isbn: "978-1449486792",
    pages: 256,
    format: "both",
  },

  // Comic Books
  {
    id: "30",
    title: "Watchmen",
    author: "Alan Moore",
    description:
      "A hit HBO series from Damon Lindelof and an acclaimed graphic novel from the legendary Alan Moore, Watchmen is set in an alternate 1985 America in which costumed superheroes are part of the fabric of everyday society, and the 'Doomsday Clock' - which charts the USA's tension with the Soviet Union - is permanently set at five minutes to midnight.",
    price: 19.99,
    coverImage: "/images/watchmen.jpg",
    category: "comic books",
    rating: 4.8,
    reviews: 4567,
    publisher: "DC Comics",
    publicationDate: "September 1986",
    isbn: "978-1401245252",
    pages: 416,
    format: "physical",
  },
  {
    id: "31",
    title: "The Walking Dead: Compendium One",
    author: "Robert Kirkman",
    description:
      "The Walking Dead Compendium is here! Since 2003, Robert Kirkman's The Walking Dead has been redefining the survival horror genre with its unique and vivid account of life after the end of the world.",
    price: 39.99,
    coverImage: "/images/walking-dead.jpg",
    category: "comic books",
    rating: 4.6,
    reviews: 2134,
    publisher: "Image Comics",
    publicationDate: "May 19, 2009",
    isbn: "978-1607060765",
    pages: 1088,
    format: "physical",
  },
  {
    id: "32",
    title: "Batman: Year One",
    author: "Frank Miller",
    description:
      "In 1987, Frank Miller revolutionized comics with this dark take on Batman's origin. Frank Miller's Batman: Year One changed the comic book industry by creating the first four-issue story arc.",
    price: 14.99,
    coverImage: "/images/batman-year-one.jpg",
    category: "comic books",
    rating: 4.7,
    reviews: 3421,
    publisher: "DC Comics",
    publicationDate: "October 1987",
    isbn: "978-1401207526",
    pages: 144,
    format: "physical",
  },
  {
    id: "33",
    title: "Saga Volume 1",
    author: "Brian K. Vaughan",
    description:
      "When two soldiers from opposite sides of a never-ending galactic war fall in love, they risk everything to bring a fragile new life into a dangerous old universe.",
    price: 12.99,
    coverImage: "/images/saga-vol1.jpg",
    category: "comic books",
    rating: 4.5,
    reviews: 1987,
    publisher: "Image Comics",
    publicationDate: "October 10, 2012",
    isbn: "978-1607066019",
    pages: 160,
    format: "physical",
  },
  {
    id: "34",
    title: "Sandman Vol. 1: Preludes & Nocturnes",
    author: "Neil Gaiman",
    description:
      "New York Times best-selling author Neil Gaiman's transcendent series SANDMAN is often hailed as the definitive Vertigo title and one of the finest achievements in graphic storytelling.",
    price: 16.99,
    coverImage: "/images/sandman-vol1.jpg",
    category: "comic books",
    rating: 4.6,
    reviews: 2876,
    publisher: "Vertigo",
    publicationDate: "August 1991",
    isbn: "978-1401284770",
    pages: 240,
    format: "physical",
  },

  // Young Adult
  {
    id: "35",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    description:
      "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.",
    price: 12.99,
    coverImage: "/images/hunger-games.jpg",
    category: "young adult",
    rating: 4.4,
    reviews: 5432,
    publisher: "Scholastic Press",
    publicationDate: "September 14, 2008",
    isbn: "978-0439023481",
    pages: 374,
    format: "both",
  },
  {
    id: "36",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    description:
      "Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified Harry will learn that he's really a wizard, just as his parents were.",
    price: 8.99,
    coverImage: "/images/harry-potter.jpg",
    category: "young adult",
    rating: 4.8,
    reviews: 8765,
    publisher: "Scholastic",
    publicationDate: "June 26, 1997",
    isbn: "978-0439708180",
    pages: 309,
    format: "both",
  },

  // Health & Fitness
  {
    id: "37",
    title: "The 4-Hour Body",
    author: "Timothy Ferriss",
    description:
      "An uncommon guide to rapid fat-loss, incredible sex, and becoming superhuman. For decades, we've been told that the key to health and weight loss is moderation, time, and suffering. But what if it's not?",
    price: 16.99,
    coverImage: "/images/4-hour-body.jpg",
    category: "health & fitness",
    rating: 4.1,
    reviews: 1876,
    publisher: "Crown Archetype",
    publicationDate: "December 14, 2010",
    isbn: "978-0307463630",
    pages: 592,
    format: "both",
  },
  {
    id: "38",
    title: "Becoming a Supple Leopard",
    author: "Kelly Starrett",
    description:
      "The definitive book on movement and mobility by Dr. Kelly Starrett, a San Francisco CrossFit gym owner and physical therapist who has revolutionized how athletes think about human movement and athletic performance.",
    price: 24.99,
    coverImage: "/images/supple-leopard.jpg",
    category: "health & fitness",
    rating: 4.3,
    reviews: 987,
    publisher: "Victory Belt Publishing",
    publicationDate: "April 23, 2013",
    isbn: "978-1628600834",
    pages: 400,
    format: "both",
  },

  // Travel
  {
    id: "39",
    title: "A Walk in the Woods",
    author: "Bill Bryson",
    description:
      "The AT offers an astonishing landscape of silent forests and sparkling lakes—and to a writer with the comic genius of Bill Bryson, it also provides endless opportunities to witness the majestic silliness of his fellow human beings.",
    price: 13.99,
    coverImage: "/images/walk-woods.jpg",
    category: "travel",
    rating: 4.2,
    reviews: 2134,
    publisher: "Broadway Books",
    publicationDate: "May 4, 1998",
    isbn: "978-0767902526",
    pages: 397,
    format: "both",
  },
  {
    id: "40",
    title: "Wild",
    author: "Cheryl Strayed",
    description:
      "At twenty-two, Cheryl Strayed thought she had lost everything. In the wake of her mother's death, her family scattered and her own marriage was soon destroyed. Four years later, with nothing more to lose, she made the most impulsive decision of her life: to hike the Pacific Crest Trail from the Mojave Desert through California and Oregon to Washington State—and to do it alone.",
    price: 14.99,
    coverImage: "/images/wild.jpg",
    category: "travel",
    rating: 4.1,
    reviews: 3421,
    publisher: "Knopf",
    publicationDate: "March 20, 2012",
    isbn: "978-0307592736",
    pages: 336,
    format: "both",
  },
]

export const featuredBooks = allBooks.slice(0, 8)
